apiVersion: argoprojlabs.argoproj-labs.io/v1
kind: Token
metadata:
  name: token-sample
  namespace: argocd
spec:
  # Add fields here
  project: default
  role: TestRole
  argocdendpt: http://localhost:9000
  expiresin: 30
  secretRef:
    name: testsecret
    key: testkey