apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: token-controller
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  destinations:
  - namespace: 'argo-cd-tokens-system'
    server: 'https://kubernetes.default.svc'
  roles:
  - name: ci-deployer
    policies:
    - p, proj:token-controller:ci-deployer, applications, get, token-controller/*, allow
    - p, proj:token-controller:ci-deployer, applications, sync, token-controller/*, allow
    - p, proj:token-controller:ci-deployer, applications, delete, token-controller/*, deny
  sourceRepos:
  - 'https://github.com/argoproj-labs/argo-cd-tokens.git'